### PR TITLE
Created quote component

### PR DESCRIPTION
**Pull request by sodabarauf**
this is first project of react app here I did this work:
-followed GitHub flow work
-created react app
-added descriptive readme.md file
-added linters
-added some tags to App.js root component
-added some functions
-added some styles
-deleted unnecessary files

### CODE REVIEW

**Comment by sodabarauf** [comment]
@ahzamir
hello sir, hope doing well.
this is the first project of react which I worked for second time cause my previous repository due to some problems fail and by force I worked again.
thank you

**Comment by humuyar** [comment]
hi @sodabarauf  jan 
i review your project u should add some content about your project in read me file. other part are done.

**Review by ahzamir — CHANGES_REQUESTED** [review]
@sodabarauf 

Hey Sodaba, your project does not show random quotes, and besides that, your README.md file does not contain information about your project solve these issues and ask for a re-review.

**Comment by sodabarauf** [comment]
> @sodabarauf
> 
> Hey Sodaba, your project does not show random quotes, and besides that, your README.md file does not contain information about your project solve these issues and ask for a re-review.

@ahzamir 
sir I solved the problems and implemented your feedback you can re-review, hope it be acceptable.
thank you.

**Review by ahzamir — APPROVED** [review]
### Hi @sodabarauf 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF


 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Random quote machine project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by sodabarauf** [comment]
@ahzamir 
hello sir, thanks from all your feedback and supports.

**Pull request merged**
